# Site settings
title:
email:
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: D. Ernest
email: devon@postghost.co
facebook_username:
twitter_username: @postghostmusic
github_username:
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone: (608) 669-6975
copyright: Post Ghost Production Company.  All rights reserved

# API settings
google_api_key:

# Build settings
markdown: kramdown
